# Generated by Django 3.1.5 on 2021-01-31 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id_bebida', models.AutoField(primary_key=True, serialize=False)),
                ('nombreBebida', models.CharField(max_length=300)),
                ('costoBebida', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nombreIngrediente', models.CharField(max_length=300)),
                ('costoIngrediente', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPedido', models.DateField(verbose_name='Fecha pedido')),
                ('nombreCliente', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id_sandwich', models.AutoField(primary_key=True, serialize=False)),
                ('fk_pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('id_tamano', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTamano', models.CharField(max_length=300)),
                ('costoTamano', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich_Ingrediente',
            fields=[
                ('id_sandwich_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('fk_ingrediente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.ingrediente')),
                ('fk_sandwich', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.sandwich')),
            ],
        ),
        migrations.AddField(
            model_name='sandwich',
            name='fk_tamano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.tamano'),
        ),
        migrations.CreateModel(
            name='Bebida_Sandwich',
            fields=[
                ('id_bebida_sandwich', models.AutoField(primary_key=True, serialize=False)),
                ('fk_bebida', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.bebida')),
                ('fk_sandwich', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.sandwich')),
            ],
        ),
    ]
